apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: backend
spec: 
 replicas: 2
 strategy: 
  type: RollingUpdate 
 selector: 
  matchLabels: 
   app: backend 
 template: 
   metadata: 
    labels: 
     app: backend
     env: prod 
   spec: 
    containers: 
    - name: backend
      image: chaimakh/backend:latest
