apiVersion: v1
kind: Service
metadata:
 name: backend
spec:
 type: NodePort
 selector:
   app: backend
   env: prod
 ports:
 - name: test1
   protocol: TCP
   port: 880
   targetPort: 880
   nodePort: 880
